/**
 *  Billing Api 
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { BillingDtoBillingModel } from '../model/models';
import { CreateBillingCommandBillingModel } from '../model/models';
import { PatchBillingCommandBillingModel } from '../model/models';
import { ProblemDetailsBillingModel } from '../model/models';


import { BillingConfiguration }                                     from '../configuration';


export interface ApiBillingsGetRequestParams {
    name?: string;
    observations?: string;
    queryValue?: string;
    workName?: string;
    receptionDateFrom?: string;
    receptionDateTo?: string;
    amountFrom?: number;
    amountTo?: number;
    page?: number;
    pageSize?: number;
    order?: string;
    ids?: Array<string>;
}

export interface ApiBillingsIdDeleteRequestParams {
    id: number;
}

export interface ApiBillingsIdGetRequestParams {
    id: number;
}

export interface ApiBillingsIdPatchRequestParams {
    id: number;
    patchBillingCommandBillingModel?: PatchBillingCommandBillingModel;
}

export interface ApiBillingsPostRequestParams {
    createBillingCommandBillingModel?: CreateBillingCommandBillingModel;
}


export interface BillingsBillingServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: BillingConfiguration;

    /**
     * 
     * 
     * @endpoint get /api/billings
* @param requestParameters
     */
    apiBillingsGet(requestParameters: ApiBillingsGetRequestParams, extraHttpRequestParams?: any): Observable<Array<BillingDtoBillingModel>>;

    /**
     * 
     * 
     * @endpoint delete /api/billings/{id}
* @param requestParameters
     */
    apiBillingsIdDelete(requestParameters: ApiBillingsIdDeleteRequestParams, extraHttpRequestParams?: any): Observable<boolean>;

    /**
     * 
     * 
     * @endpoint get /api/billings/{id}
* @param requestParameters
     */
    apiBillingsIdGet(requestParameters: ApiBillingsIdGetRequestParams, extraHttpRequestParams?: any): Observable<BillingDtoBillingModel>;

    /**
     * 
     * 
     * @endpoint patch /api/billings/{id}
* @param requestParameters
     */
    apiBillingsIdPatch(requestParameters: ApiBillingsIdPatchRequestParams, extraHttpRequestParams?: any): Observable<BillingDtoBillingModel>;

    /**
     * 
     * 
     * @endpoint post /api/billings
* @param requestParameters
     */
    apiBillingsPost(requestParameters: ApiBillingsPostRequestParams, extraHttpRequestParams?: any): Observable<BillingDtoBillingModel>;

}
