/**
 *  Billing Api 
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { PatchWorkCommandBillingModel } from '../model/models';
import { PostWorkCommandBillingModel } from '../model/models';
import { WorkDtoBillingModel } from '../model/models';


import { BillingConfiguration }                                     from '../configuration';


export interface ApiWorksGetRequestParams {
    page?: number;
    pageSize?: number;
    order?: string;
    ids?: Array<string>;
}

export interface ApiWorksIdGetRequestParams {
    id: number;
}

export interface ApiWorksIdPatchRequestParams {
    id: number;
    patchWorkCommandBillingModel?: PatchWorkCommandBillingModel;
}

export interface ApiWorksPostRequestParams {
    postWorkCommandBillingModel?: PostWorkCommandBillingModel;
}


export interface WorksBillingServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: BillingConfiguration;

    /**
     * 
     * 
     * @endpoint get /api/works
* @param requestParameters
     */
    apiWorksGet(requestParameters: ApiWorksGetRequestParams, extraHttpRequestParams?: any): Observable<Array<WorkDtoBillingModel>>;

    /**
     * 
     * 
     * @endpoint get /api/works/{id}
* @param requestParameters
     */
    apiWorksIdGet(requestParameters: ApiWorksIdGetRequestParams, extraHttpRequestParams?: any): Observable<WorkDtoBillingModel>;

    /**
     * 
     * 
     * @endpoint patch /api/works/{id}
* @param requestParameters
     */
    apiWorksIdPatch(requestParameters: ApiWorksIdPatchRequestParams, extraHttpRequestParams?: any): Observable<WorkDtoBillingModel>;

    /**
     * 
     * 
     * @endpoint post /api/works
* @param requestParameters
     */
    apiWorksPost(requestParameters: ApiWorksPostRequestParams, extraHttpRequestParams?: any): Observable<WorkDtoBillingModel>;

}
